### ISSUE TITLE
Remove secrets

### ISSUE THREAD

**Issue by alfunx** [dk0104/MyDotFiles#1]
https://github.com/dk0104/MyDotFiles/blob/fc3166b2f8ace615a9573af4222d9c92c8f87ff8/ZSH/.zshrc#L5

You should probably put such things in some dedicated file, e.g. `~/.secrets`. You could put it as-is in the file and then in your `.zshrc` say `source ~/.secrets`. Consider deleting the token and recreating a new one.

**Comment by dk0104** [comment]
Oh.. Thanks for Advice.
